//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace k2vr_installer_gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("k2vr_installer_gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the download(s)?.
        /// </summary>
        public static string download_cancel {
            get {
                return ResourceManager.GetString("download_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join our Discord server for further assistance:.
        /// </summary>
        public static string download_failed_discord {
            get {
                return ResourceManager.GetString("download_failed_discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to join.
        /// </summary>
        public static string download_failed_discord_button {
            get {
                return ResourceManager.GetString("download_failed_discord_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason:.
        /// </summary>
        public static string download_failed_reason {
            get {
                return ResourceManager.GetString("download_failed_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed!.
        /// </summary>
        public static string download_failed_title {
            get {
                return ResourceManager.GetString("download_failed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this window.
        /// </summary>
        public static string finish_close_button {
            get {
                return ResourceManager.GetString("finish_close_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We also highly recommend joining our Discord server for updates and support:.
        /// </summary>
        public static string finish_discord {
            get {
                return ResourceManager.GetString("finish_discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Discord.
        /// </summary>
        public static string finish_discord_button {
            get {
                return ResourceManager.GetString("finish_discord_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We recommend restarting your computer now..
        /// </summary>
        public static string finish_restart {
            get {
                return ResourceManager.GetString("finish_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for installing KinectToVR!.
        /// </summary>
        public static string finish_thanks {
            get {
                return ResourceManager.GetString("finish_thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit our website for further instructions:.
        /// </summary>
        public static string finish_website {
            get {
                return ResourceManager.GetString("finish_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit website.
        /// </summary>
        public static string finish_website_button {
            get {
                return ResourceManager.GetString("finish_website_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Installation.
        /// </summary>
        public static string home_begin_button {
            get {
                return ResourceManager.GetString("home_begin_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By proceeding with the installation you agree that this software is provided to you &quot;as is&quot; without any warranty whatsoever. In no event shall the authors of this software be liable for any claim, damages or other liability..
        /// </summary>
        public static string home_disclaimer {
            get {
                return ResourceManager.GetString("home_disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string home_language_button {
            get {
                return ResourceManager.GetString("home_language_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Open Source Licenses.
        /// </summary>
        public static string home_licenses_button {
            get {
                return ResourceManager.GetString("home_licenses_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy K2VR Found!.
        /// </summary>
        public static string instal_legacy_k2vr_remove_title {
            get {
                return ResourceManager.GetString("instal_legacy_k2vr_remove_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to delete your calibration settings as well?
        ///To resuse them you will need to install KinectToVR in the directory {0} again.
        ///Delete calibration settings?.
        /// </summary>
        public static string install_calibration_remove {
            get {
                return ResourceManager.GetString("install_calibration_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete calibration settings?.
        /// </summary>
        public static string install_calibration_remove_title {
            get {
                return ResourceManager.GetString("install_calibration_remove_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Installation.
        /// </summary>
        public static string install_completed_button {
            get {
                return ResourceManager.GetString("install_completed_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot install two versions of KinectToVR into the same directory, or install KinectToVR into a directory with existing files.
        ///Either uninstall the old version or select another, empty install directory.
        ///Restart this installer to try again..
        /// </summary>
        public static string install_existing_folder_fail {
            get {
                return ResourceManager.GetString("install_existing_folder_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling legacy K2VR will delete the folder {0} and all it&apos;s contents..
        /// </summary>
        public static string install_legacy_k2vr_confirm {
            get {
                return ResourceManager.GetString("install_legacy_k2vr_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string install_legacy_k2vr_confirm_title {
            get {
                return ResourceManager.GetString("install_legacy_k2vr_confirm_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy K2VR installation found!
        ///Do you wish to uninstall it? (Recommended).
        /// </summary>
        public static string install_legacy_k2vr_remove {
            get {
                return ResourceManager.GetString("install_legacy_k2vr_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy K2VR found!.
        /// </summary>
        public static string install_legacy_k2vr_remove_title {
            get {
                return ResourceManager.GetString("install_legacy_k2vr_remove_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple installations of K2EX risk interfering with each other.
        ///Restart this installer to try again
        ///Please join our Discord for further assistance (Link on k2vr.tech).
        /// </summary>
        public static string install_multiple_k2ex {
            get {
                return ResourceManager.GetString("install_multiple_k2ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenVR Input Emulator was found. we strongly recommend removing it as it&apos;s been rendered obselete by recent versions of SteamVR..
        /// </summary>
        public static string install_remove_ovrie {
            get {
                return ResourceManager.GetString("install_remove_ovrie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to uninstall OpenVR Input Emulator?.
        /// </summary>
        public static string install_remove_ovrie_title {
            get {
                return ResourceManager.GetString("install_remove_ovrie_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect SDK was not installed successfully
        ///Restart this installer to try again
        ///Please join our Discord for further assistance (Link on k2vr.tech).
        /// </summary>
        public static string install_sdk_failed {
            get {
                return ResourceManager.GetString("install_sdk_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t close SteamVR, please close it manually and try running this installer again!.
        /// </summary>
        public static string install_steamvr_close_failed {
            get {
                return ResourceManager.GetString("install_steamvr_close_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to permanently delete the (old) installation directory {0} and all of it&apos;s contents?.
        /// </summary>
        public static string install_uninstall_confirm {
            get {
                return ResourceManager.GetString("install_uninstall_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove old installation?.
        /// </summary>
        public static string install_uninstall_title {
            get {
                return ResourceManager.GetString("install_uninstall_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory {0} contains user-created files.
        ///Clicking OK will open the directory in a file explorer window for you to look into..
        /// </summary>
        public static string install_unknown_files {
            get {
                return ResourceManager.GetString("install_unknown_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KinectToVR appears to be already installed in {0}
        ///Do you wish to update this installation?.
        /// </summary>
        public static string install_update {
            get {
                return ResourceManager.GetString("install_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm update?.
        /// </summary>
        public static string install_update_title {
            get {
                return ResourceManager.GetString("install_update_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K2EX appears to also be installed in {0}. Do you wish to disable it?.
        /// </summary>
        public static string installer_previous_disable {
            get {
                return ResourceManager.GetString("installer_previous_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Installed.
        /// </summary>
        public static string installer_previous_disable_title {
            get {
                return ResourceManager.GetString("installer_previous_disable_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string lang_native {
            get {
                return ResourceManager.GetString("lang_native", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow sending anonymous usage data.
        /// </summary>
        public static string setup_allow_analytics_button {
            get {
                return ResourceManager.GetString("setup_allow_analytics_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What data is being collected?.
        /// </summary>
        public static string setup_analytics_info {
            get {
                return ResourceManager.GetString("setup_analytics_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string setup_change_location_button {
            get {
                return ResourceManager.GetString("setup_change_location_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected.
        /// </summary>
        public static string setup_device_detected {
            get {
                return ResourceManager.GetString("setup_device_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remembered.
        /// </summary>
        public static string setup_device_known {
            get {
                return ResourceManager.GetString("setup_device_known", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected.
        /// </summary>
        public static string setup_device_selected {
            get {
                return ResourceManager.GetString("setup_device_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device selected!.
        /// </summary>
        public static string setup_device_unselected {
            get {
                return ResourceManager.GetString("setup_device_unselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and install now.
        /// </summary>
        public static string setup_install_button {
            get {
                return ResourceManager.GetString("setup_install_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select install location:.
        /// </summary>
        public static string setup_location {
            get {
                return ResourceManager.GetString("setup_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid install location!.
        /// </summary>
        public static string setup_location_invalid {
            get {
                return ResourceManager.GetString("setup_location_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No install location selected!.
        /// </summary>
        public static string setup_location_unselected {
            get {
                return ResourceManager.GetString("setup_location_unselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which device you intend to use:.
        /// </summary>
        public static string setup_selection {
            get {
                return ResourceManager.GetString("setup_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string tabs_download {
            get {
                return ResourceManager.GetString("tabs_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string tabs_finish {
            get {
                return ResourceManager.GetString("tabs_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string tabs_home {
            get {
                return ResourceManager.GetString("tabs_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string tabs_install {
            get {
                return ResourceManager.GetString("tabs_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string tabs_setup {
            get {
                return ResourceManager.GetString("tabs_setup", resourceCulture);
            }
        }
    }
}
